TestApplication/TestApplication/Models/Invoices.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestApplication.Models
{
    public class Invoices
    {
        [DisplayName("Invoice Id")]
        public int ID { get; set; }

        [DisplayName("Date Of Sale")]
        public DateTime SaleDate { get; set; }

        [DisplayName("Total Amount")]
        public double InvoiceTotal { get; set; }

        [Required(ErrorMessage = "Please Enter Customer Name")]
        [DisplayName("Customer Name")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Please Enter Product Name")]
        [DisplayName("Product Name")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Please Enter Cost Per Unit")]
        [DisplayName("Cost Per Unit")]
        [Range(1, 1000,
            ErrorMessage = "Cost Per Unit must be between 1 and 1000")]
        public int CostPerUnit { get; set; }

        [Required(ErrorMessage = "Please Enter Product Quantity")]
        [Range(1, 100,
            ErrorMessage = "Quantity must be between 1 and 100")]
        public int Quantity { get; set; }

        [NotMapped]
        public int Discount { get; set; }
        [NotMapped]
        public IEnumerable<SelectListItem> ProductList { get; set; }

    }
}

TestApplication/TestApplication/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestApplication.DAL;
using TestApplication.Models;

namespace TestApplication.Controllers
{
    public class InvoicesController : Controller
    {
        private ContosoContext db = new ContosoContext();

        // GET: Invoices
        public ActionResult Index()
        {
            var allInvoices = db.Invoices.ToList();
            var DailySales = allInvoices.Where(x=>x.SaleDate.Month==DateTime.Today.Month && x.SaleDate.Year == DateTime.Today.Year && x.SaleDate.Day == DateTime.Today.Day).ToList();
            if(allInvoices!=null)
            ViewBag.OverallSale = allInvoices.Sum(x => x.InvoiceTotal);
            if (DailySales != null)
                ViewBag.DailySale = DailySales.Sum(x => x.InvoiceTotal);

            return View(DailySales);
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            var allProductList = db.Products.Where(x=>x.StockAvailable>0).ToList();
            List<SelectListItem> ListOfItems = new List<SelectListItem>();
            foreach(var product in allProductList)
            {
                ListOfItems.Add(new SelectListItem { Text = product.ProductName, Value = product.ID.ToString() });
            }
            Invoices invoiceObj = new Invoices();
            invoiceObj.ProductList = ListOfItems;
            return View(invoiceObj);
        }
        [HttpPost]
        public ActionResult FetchCostPerUnit(string productName)
        {
            if (!string.IsNullOrEmpty(productName))
            {
                var product = db.Products.Where(s => s.ID.ToString() == productName).FirstOrDefault<Product>();
                return Json(new { product.Cost }, JsonRequestBehavior.AllowGet );
            }
            return null;
        }
        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Invoices invoices)
        {
            if (ModelState.IsValid)
            {
                bool isStockAvailable = false;
                var product = db.Products.Where(s => s.ID.ToString() == invoices.ProductName).FirstOrDefault<Product>();
                if(product.StockAvailable>invoices.Quantity)
                {
                    product.StockAvailable = product.StockAvailable - invoices.Quantity;
                    db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    isStockAvailable = true;
                }
                else
                {
                    ViewBag.Message = "Ooops..Insufficient stock for selected product";
                }
                if (isStockAvailable)
                {
                    invoices.SaleDate = DateTime.Now;
                    invoices.InvoiceTotal = ((invoices.CostPerUnit * invoices.Quantity) - invoices.Discount);
                    var tax = 0.04 * invoices.InvoiceTotal;
                    invoices.InvoiceTotal = invoices.InvoiceTotal + tax;
                    invoices.InvoiceTotal = ((invoices.CostPerUnit * invoices.Quantity)-invoices.Discount) + tax;
                    db.Invoices.Add(invoices);
                    db.SaveChanges();

                    // decrement product stock
                    ViewBag.Message = "Invoice Added Successfully.";
                }

                return RedirectToAction("Create");
            }
            ViewBag.Message = "Error while saving record in Database.";

            return View(invoices);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Invoices invoices)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoices).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invoices);
        }

        // GET: Invoices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = db.Invoices.Find(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoices invoices = db.Invoices.Find(id);
            db.Invoices.Remove(invoices);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestApplication/TestApplication/Views/Invoices/Create.cshtml
@model TestApplication.Models.Invoices

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoices</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            @ViewBag.Message
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProductName, Model.ProductList, "Select" ,new { onchange = "GetProductDefaultCost(this.value)" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger"})
            </div>
        </div>


        <div class="form-group calculation" style="display:none;">
            Total= <input type="number" id="Total_cal" />
            Discount=<input type="number" id="Discount_cal" />
            Tax=<input type="number" id="Tax_cal" />
            Final Amount is <input type="number" id="FinalAmount_cal" />
        </div>


       



        <div class="form-group">
            <div class="col-md-offset-2 col-md-1">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
           
            <a href="@Url.Action("Index", "Invoices")" class="btn btn-danger col-md-1">Cancel</a>

            <a href="@Url.Action("Index", "Invoices")" class="btn btn-default col-md-1">Exit</a>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    function GetProductDefaultCost(productName)
    {
        productName = $("#ProductName").val();
       // alert('Test Successful');
    $.ajax({
        dataType: "application/json",
        type: "POST",
        data: { productName : productName },
        url: "/Invoices/FetchCostPerUnit",
        success: function (data) {
            console.log(data);
            $('#CostPerUnit').val(data);
        }
    });
    }
    $("#Quantity").change(function () {
        var Tax = 0.04;
        $('.calculation').show();
        var CostPerUnit = $('#CostPerUnit').val();
        var Quantity = $('#Quantity').val();
        var Discount = $('#Discount').val();

        var amount = (CostPerUnit * Quantity);
        $('#Total_cal').val(amount);
        amount = (CostPerUnit * Quantity) - Discount;


        var taxAmount = amount * Tax;
        amount = amount + taxAmount;
        $('#Discount_cal').val(Discount);
        $('#Tax_cal').val(taxAmount);
        $('#FinalAmount_cal').val(amount);



    });
    </script>
}

TestApplication/TestApplication/Views/Invoices/Delete.cshtml
@model TestApplication.Models.Invoices

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoices</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SaleDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TestApplication/TestApplication/Views/Invoices/Details.cshtml
@model TestApplication.Models.Invoices

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoices</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SaleDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SaleDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TestApplication/TestApplication/Views/Invoices/Edit.cshtml
@model TestApplication.Models.Invoices

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoices</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.SaleDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SaleDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SaleDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestApplication/TestApplication/Views/Invoices/Index.cshtml
@model IEnumerable<TestApplication.Models.Invoices>

@{
    ViewBag.Title = "Index";
}


<p>
    @Html.ActionLink("Register Invoice", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SaleDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InvoiceTotal)
        </th>
       
                <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SaleDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InvoiceTotal)
        </td>
      
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>*@
    </tr>
}

</table>
<hr />
<footer>
    <p style="color:green;">Overall Sale=@ViewBag.OverallSale ,Todays sale= @ViewBag.DailySale </p>
</footer>